from pathlib import Path


def build_project(project_name):
    project = Path(project_name)
    project.mkdir(exist_ok=True)

    files = {
        "README.md": f"# {project_name}\n\nGenerated by AICompany OS\n",

        "requirements.txt": """fastapi
uvicorn
""",

        ".gitignore": """.venv/
__pycache__/
.env
""",

        "main.py": """from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message": "Hello AICompany"}
"""
    }

    for filename, content in files.items():
        (project / filename).write_text(content, encoding="utf-8")

    print(f"✅ {project_name} 프로젝트 생성 완료")